from collections import OrderedDict


clear = OrderedDict({
   r'(Chapter.*?)\s*\[.*?Amazon.*?\].*?': r'\1',
   r'.+(?:Amazon|Royal Road).+': '',
   r'.*Unauthorized.*?:.+': '',
   r'.*author.*(?:platform|public|novel|version|report|Report).+': '',
   r'.*(?:novel|site|platform).*(?:author|public).+': '',
   r'.*pirate.*copy.+': '',
   r'.*Stole.*report.+': '',
})

replace_prefix = '['
replace_postfix = ']'

not_prefix_tmp_replace = '{'
not_postfix_tmp_replace = '}'

replacements = OrderedDict({
   "Noah": {'t': 'Ной', 'context': "he"},
   "Moxie": {'t': 'Мокси', 'context': "she"},
   "Lee": {'t': 'Ли', 'context': "she"},
   "Wizen": {'t': 'Визен', 'context': "he"},
   "Aylin": {'t': 'Айлин', 'context': "she"},
   "Spider": {'t': 'Паук', 'context': "he"},
   "Silvertide": {'t': 'Сильвертид', 'context': "he"},
   "Violet": {'t': 'Вайолет', 'context': "she"},
   "Yoru": {'t': 'Йору', 'context': "he"},
   "Vrith": {'t': 'Врит', 'context': "he"},
   "Tim": {'t': 'Тим', 'context': "he"},
   "Alexandra": {'t': 'Александра', 'context': "she"},
   "Todd": {'t': 'Тодд', 'context': "he"},
   "Sievan": {'t': 'Сиван', 'context': "he"},
   "Jalen": {'t': 'Джален', 'context': "he"},
   "Emily": {'t': 'Эмили', 'context': "she"},
   "Axil": {'t': 'Аксиль', 'context': "she"},
   "Renewal": {'t': 'Возрождение', 'context': "she"},
   "Brayden": {'t': 'Брейден', 'context': "he"},
   "Vermil": {'t': 'Вермил', 'context': "he"},
   "Pirren": {'t': 'Пиррена', 'context': "she"},
   "Isabel": {'t': 'Изабель', 'context': "she"},
   "Decras": {'t': 'Декрас', 'context': "he"},
   "Zath": {'t': 'Зат', 'context': "he"},
   "Belkus": {'t': 'Белкус', 'context': "he"},
   "Lord": {'t': 'Лорд', 'context': "he"},
   "Azel": {'t': 'Азель', 'context': "he"},
   "Sunder": {'t': 'Разлом', 'context': "he"},
   "Bird": {'t': 'Бёрд', 'context': "she"},
   "Ulya": {'t': 'Улия', 'context': "she"},
   "James": {'t': 'Джеймс', 'context': "he"},
   "Arbitage": {'t': 'Арбитраж', 'context': "he"},
   "Godrick": {'t': 'Годрик', 'context': "he"},
   "Igris": {'t': 'Игрис', 'context': "he"},
   "Barb": {'t': 'Барба', 'context': "she"},
   "Yoku": {'t': 'Йоку', 'context': "she"},
   "Rafael": {'t': 'Рафаэль', 'context': "he"},
   "Yulin": {'t': 'Юлина', 'context': "she"},
   "Zorin": {'t': 'Зорин', 'context': "he"},
   "Otto": {'t': 'Отто', 'context': "he"},
   "Mascot": {'t': 'Маскот', 'context': "he"},
   "Golon": {'t': 'Голон', 'context': "he"},
   "Matis": {'t': 'Матис', 'context': "he"},
   "Verrud": {'t': 'Верруд', 'context': "he"},
   "Treadon": {'t': 'Трэдон', 'context': "he"},
   "Marley": {'t': 'Марли', 'context': "he"},
   "Enforcers": {'t': 'Исполнители'},
   "Rekeba": {'t': 'Рекеба', 'context': "she"},
   "Jakob": {'t': 'Якоб', 'context': "he"},
   "Revin": {'t': 'Ревин', 'context': "he"},
   "Sinclaire": {'t': 'Синклер', 'context': "she"},
   "Vroth": {'t': 'Фрот', 'context': "he"},
   "Edda": {'t': 'Эдда', 'context': "she"},
   "Torrin": {'t': 'Торрин', 'context': "he"},
   "Taleel": {'t': 'Талил', 'context': "he"},
   "Neir": {'t': 'Нейр', 'context': "he"},
   "Robon": {'t': 'Робон', 'context': "he"},
   "Torick": {'t': 'Торик', 'context': "he"},
   "Torrins": {'t': 'Торринс', 'context': "he"},
   "Judgement": {'t': 'Правосудие', 'context': "she"},
   "Mayreena": {'t': 'Майрина', 'context': "she"},
   "Evergreen": {'t': 'Эвергрин', 'context': "she"},
   "Linwick": {'t': 'Линвик', 'context': "they"},
   "Audren": {'t': 'Одрен', 'context': "he"},
   "Gero": {'t': 'Геро', 'context': "he"},
   "Joe": {'t': 'Джо', 'context': "he"},
   "Gex": {'t': 'Гекс', 'context': "he"},
   "Enforcer": {'t': 'Исполнитель', 'context': "he"},
   "Contessa": {'t': 'Контесса', 'context': "he"},
   "Mikthal": {'t': 'Миктал', 'context': "he"},
   "Yog": {'t': 'Йог', 'context': "he"},
   "Web": {'t': 'Сеть', 'context': "organization"},
   "Garina": {'t': 'Гарина', 'context': "she"},
   "Karina": {'t': 'Карина', 'context': "she"},
   "Gentil": {'t': 'Джентил', 'context': "he"},
   "Fiona": {'t': 'Фиона', 'context': "she"},
   "Imbuements": {'t': 'Наполнения', 'context': "he"},
   "Imbuement": {'t': 'Наполнение', 'context': "he"},
   "imbuement": {'t': 'наполнение', 'context': "he"},
   "Goddess": {'t': 'Богиня', 'context': "she"},
   "Janice": {'t': 'Дженис', 'context': "she"},
   "Hoarder": {'t': 'Хранитель', 'context': "she"},
   "advanced track": {'t': 'продвинутая группа'},
   "Advanced Track": {'t': 'Продвинутая Группа'},
})